// frontend-react/src/components/Skills/index.jsx
import React from 'react';

import Skill from './Skill';

import './Skills.css';
import python from '../../assets/svgs/colored/python.svg';
import django from '../../assets/svgs/colored/django.svg';
import cplusplus from '../../assets/svgs/colored/c++.svg';
import c from '../../assets/svgs/colored/c.svg';
import node from '../../assets/svgs/colored/nodejs.svg';
import mysql from '../../assets/svgs/colored/mysql.svg';
import postgresql from '../../assets/svgs/colored/postgresql.svg';

import css3 from '../../assets/svgs/css3.svg';
import html5 from '../../assets/svgs/html5.svg';
import vue from '../../assets/svgs/colored/vue.svg';
import reactjs from '../../assets/svgs/colored/reactjs.svg';
import bootstrap from '../../assets/svgs/colored/bootstrap.svg';
import bulma from '../../assets/svgs/colored/bulma.svg';

import github from '../../assets/svgs/colored/github-icon.svg';
import bitbucket from '../../assets/svgs/colored/bitbucket.svg';
import aws from '../../assets/svgs/colored/aws.svg';
import heroku from '../../assets/svgs/heroku.svg';
import confluence from '../../assets/svgs/colored/confluence.svg';
import jira from '../../assets/svgs/colored/jira.svg';

function Skills() {
  return (
    <div id="skills">
      <div className="columns is-centered">
        <Skill imgSrc={python} skill="Python" colSize="is-1" />
        <Skill imgSrc={c} skill="C" colSize="is-1" />
        <Skill imgSrc={cplusplus} skill="C++" colSize="is-1" />
      </div>
      <div className="columns">
        <div className="column">
          <h1 className="skills-header">Back-End</h1>
          <div className="columns is-centered">
            <Skill imgSrc={django} skill="Django" colSize="is-one-third" />
            <Skill imgSrc={node} skill="Node" colSize="is-one-third" />
          </div>
          <div className="columns is-centered">
            <Skill imgSrc={mysql} skill="MySQL" colSize="is-one-third" />
            <Skill
              imgSrc={postgresql}
              skill="PostgreSQL"
              colSize="is-one-third"
            />
          </div>
        </div>

        <div className="column">
          <h1 className="skills-header">Front-End</h1>
          <div className="columns is-centered">
            <Skill imgSrc={html5} skill="HTML" colSize="is-one-third" />
            <Skill imgSrc={css3} skill="CSS" colSize="is-one-third" />
          </div>
          <div className="columns is-centered">
            <Skill imgSrc={reactjs} skill="React" colSize="is-one-third" />
            <Skill imgSrc={vue} skill="Vue" colSize="is-one-third" />
          </div>
          <div className="columns is-centered">
            <Skill
              imgSrc={bootstrap}
              skill="Bootstrap 4"
              colSize="is-one-third"
            />
            <Skill imgSrc={bulma} skill="Bulma" colSize="is-one-third" />
          </div>
        </div>

        <div className="column">
          <h1 className="skills-header">Tools</h1>
          <div className="columns is-centered">
            <Skill imgSrc={github} skill="GitHub" colSize="is-one-third" />
            <Skill
              imgSrc={bitbucket}
              skill="Bitbucket"
              colSize="is-one-third"
            />
          </div>
          <div className="columns is-centered">
            <Skill imgSrc={aws} skill="AWS" colSize="is-one-third" />
            <Skill imgSrc={heroku} skill="heroku" colSize="is-one-third" />
          </div>
          <div className="columns is-centered">
            <Skill
              imgSrc={confluence}
              skill="Confluence"
              colSize="is-one-third"
            />
            <Skill imgSrc={jira} skill="Jira" colSize="is-one-third" />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Skills;

// frontend/src/components/Skills.vue
<script src="../router.js"></script>
<template>
  <div id="skills">
    <div class="columns is-centered">
      <div class="column is-1" data-aos="zoom-in">
        <div class="is-flex logo">
          <figure class="image is-64x64 logo">
            <img src="../assets/svgs/colored/python.svg" alt="Django" />
          </figure>
        </div>
        <h1 class="skill" id="django">Python</h1>
      </div>
      <div class="column is-1" data-aos="zoom-in">
        <div class="is-flex logo">
          <figure class="image is-64x64 logo">
            <img src="../assets/svgs/colored/c.svg" alt="Django" />
          </figure>
        </div>
        <h1 class="skill" id="django">C</h1>
      </div>
      <div class="column is-1" data-aos="zoom-in">
        <div class="is-flex logo">
          <figure class="image is-64x64 logo">
            <img src="../assets/svgs/colored/c++.svg" alt="Django" />
          </figure>
        </div>
        <h1 class="skill" id="django">C++</h1>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <h1 class="skills-header">Back-End</h1>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64 logo">
                <img src="../assets/svgs/colored/django.svg" alt="Django" />
              </figure>
            </div>
            <h1 class="skill" id="django">Django</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <figure class="image is-96x64">
              <img src="../assets/svgs/colored/nodejs.svg" alt="Node.js" />
            </figure>
            <h1 class="skill">Node.js</h1>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/mysql.svg" alt="MySQL" />
              </figure>
            </div>
            <h1 class="skill">MySQL</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/postgresql.svg" alt="PostgreSQL" />
              </figure>
            </div>

            <h1 class="skill">PostgreSQL</h1>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <img src="../assets/svgs/colored/mongodb.svg" alt="MongoDB" />
            </div>
            <h1 class="skill">MongoDB</h1>
          </div>
        </div>
      </div>

      <div class="column">
        <h1 class="skills-header">Front-End</h1>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/html5.svg" alt="HTML" />
              </figure>
            </div>
            <h1 class="skill">HTML</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/css3.svg" alt="CSS" />
              </figure>
            </div>
            <h1 class="skill">CSS</h1>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo" id="jquery">
              <figure class="image is-96x64">
                <img src="../assets/svgs/colored/jquery.svg" alt="jQuery" />
              </figure>
            </div>
            <h1 class="skill" id="jquery-text">jQuery</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/vue.svg" alt="Vue" />
              </figure>
            </div>

            <h1 class="skill">Vue</h1>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/bootstrap.svg" alt="Bootstrap" />
              </figure>
            </div>

            <h1 class="skill">Bootstrap 4</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/bulma.svg" alt="Bulma" />
              </figure>
            </div>

            <h1 class="skill">Bulma</h1>
          </div>
        </div>
      </div>

      <!-- Git, bitbucket, aws, heroku, confluence, jira  -->
      <div class="column">
        <h1 class="skills-header">Tools</h1>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64 logo">
                <img src="../assets/svgs/colored/github-icon.svg" alt="Github" />
              </figure>
            </div>
            <h1 class="skill">Github</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/bitbucket.svg" alt="Bitbucket" />
              </figure>
            </div>
            <h1 class="skill">Bitbucket</h1>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/aws.svg" alt="AWS" />
              </figure>
            </div>
            <h1 class="skill">AWS</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/heroku.svg" alt="Heroku" />
              </figure>
            </div>

            <h1 class="skill">Heroku</h1>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/confluence.svg" alt="Confluence" />
              </figure>
            </div>
            <h1 class="skill">Confluence</h1>
          </div>
          <div class="column is-one-third" data-aos="zoom-in">
            <div class="is-flex logo">
              <figure class="image is-64x64">
                <img src="../assets/svgs/colored/jira.svg" alt="Jira" />
              </figure>
            </div>
            <h1 class="skill">Jira</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>


<style scoped>
.skills-header {
  font-size: 1.25rem;
  font-weight: bold;
  margin-bottom: 1rem;
  display: inline-block;
  padding-bottom: 5px;
  position: relative;
}
.skills-header:before {
  content: "";
  position: absolute;
  width: 50%;
  height: 1px;
  bottom: 0;
  left: 25%;
  border-bottom: 2px solid red;
}

.logo {
  justify-content: center;
}
.skill {
  font-weight: bold;
  padding-top: 0.5rem;
}
#jquery,
#jquery-text {
  padding-top: 1.25rem;
}
#django {
  padding-top: 1rem;
}
</style>
